unique_ids:
  forms:
    Pizza_Oven: NVRLE7HPLVOVAKUDLXVTYEDUI7PCJHMJ
    Pizza_Oven.ItemTemplate1: NGOLRCGN76YETXGXHBCSWDSXKEZZJFTT
    Pizza_Oven.RowTemplate1: SEG576OZ5IRDPN4FKNOUZWWI2Q2BIZQL
  modules: {}
  server_modules:
    EventzAnvilAPI: CE73WTF363PFBYC7QIG5KFVGEF7T6XKL
    Pizza: BBJP7YFXEZFQVJSM5ISA4XT7WXZKOX6Q
    PizzaServerModule: 2V4YSMHLPIYRHDLVJKVVICMKN6YL74VY
    ServerModule1: M6OEWYYOFN46N2WHI7KTKS5N5UKQ77AQ
  assets:
    standard-page.html: T7OOUBRKGQRP5YAJZUO3HBHQ5QUMD5UE
    theme.css: 2TRCFL3G2WRXPFOROWNBSEK2OSQOJTAC
  scripts: {}
